### ISSUE TITLE
Cards =/= Colors

### ISSUE THREAD

**Issue by talandaw** [rhyneav/papercss#47] opened 2017-11-21 05:14 UTC
The Summary contains the link "Colors" which actually is a ref to Cards. 
Both Cards & Badges are not included in the Summary.

**Comment by afzalsayed96** [comment] 2017-11-21 06:00
Thanks for the info. I will try to fix this. @Fraham will this be considered as hotfix?

**Comment by TotomInc** [comment] 2017-11-21 06:42
I think @taladaw you looked at the wrong branch. develop branch have cards and badges on the summary, plus I can't find your issue with colors link, can you reference some lines of code please?

**Comment by talandaw** [comment] 2017-11-21 06:45
I wasn't looking at the code but just the direct website: https://www.getpapercss.com/
I'm at work so I couldn't pull the code on my work computer and was going to check back tonight.

**Comment by afzalsayed96** [comment] 2017-11-21 06:53
@TotomInc  I can confirm this. There are no links to cards and badges in summary and the link named "colors" point to cards on the main website (deployed version)

**Comment by TotomInc** [comment] 2017-11-21 06:53
Looks like someone removed some sections from the summary.

**Comment by rhyneav** [comment] 2017-11-21 15:10
That's 100% my bad @TotomInc. It must have happened when we started using the develop branch. It's in develop, but not in master. https://develop.getpapercss.com/ 

@afzalsayed96 this would be a hotfix! Could you also please add in the other items missing in the summary? I'll assign this issue to you.

**Comment by TotomInc** [comment] 2017-11-21 15:22
@rhyneav I was not aware of the develop preview, this should be added in the readme IMO.

**Comment by rhyneav** [comment] 2017-11-21 15:31
Hehe it's a brand new feature as of 22 minutes ago. I'll add in something now @TotomInc

**Closed** 2017-11-24 15:57 UTC
